# -*- coding: utf-8 -*-
"""Veri_düzenleme.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18hh9FddLxU8WgbR5pG86ryZ4wuWNp5g6
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

veri = pd.read_csv("ev_verileri.csv")
veri = veri.drop(['İlan Numarası', 'İlan Güncelleme Tarihi','Takas','Kira Getirisi', ' İlan Oluşturma Tarihi', 'WC Metrekare','Aidat','Kullanım Durumu','Balkon Metrekare',
'Balkon Durumu', 'Balkon Tipi', 'Görüntülü Gezilebilir Mi?', 'WC Sayısı', 'Kategorisi','Banyo Metrekare', 'Yatırıma Uygunluk','Balkon Sayısı', 'Yapı Tipi','Türü', 'İpotek Durumu'], axis=1)
veri.columns

veri

veri["Yapı Durumu"].fillna("İkinci El", inplace=True)
veri["Eşya Durumu"].fillna("Boş", inplace=True)
veri['Tapu Durumu'].fillna("Bilinmiyor", inplace=True)

for index, değişken in enumerate(veri['Fiyat']):
    if veri['Fiyat'][index] >= 5000000:
        veri = veri.drop(index, axis=0)
veri = veri.reset_index(level=0, drop=True)

for index, değişken in enumerate(veri['Net Metrekare']):
    veri['Net Metrekare'][index] = veri['Net Metrekare'][index].replace("M2"," ")
    veri['Net Metrekare'][index] = veri['Net Metrekare'][index].replace(" ","")
    veri['Net Metrekare'][index] = veri['Net Metrekare'][index].replace(".","")
    veri['Net Metrekare'][index] = int(veri['Net Metrekare'][index])
    if veri['Net Metrekare'][index] >= 250:
        veri = veri.drop(index, axis=0)
veri = veri.reset_index(level=0, drop=True)

veri['Net Metrekare'].unique()

for index, değişken in enumerate(veri['Brüt Metrekare']):
    veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace("M2"," ")
    veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace(" ","")
    veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace(".","")
    veri['Brüt Metrekare'][index] = int(veri['Brüt Metrekare'][index])
veri = veri.reset_index(level=0, drop=True)

veri['Brüt Metrekare'].unique()

veri = veri.dropna(subset=['Bulunduğu Kat'])
veri = veri.reset_index(level=0, drop=True)

for index, değişken in enumerate(veri['Bulunduğu Kat']):
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace(".Kat","")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Bodrum Kat',"-1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Kot 1 (-1)","-1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Kot 2 (-2)","-2")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Kot 3 (-3)","-3")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Düz Giriş (Zemin)","0")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Yüksek Giriş","1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Müstakil","1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Bahçe Katı","1")
    if değişken == "Çatı Dublex":
      veri["Tipi"][index] = "Dubleks"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Çatı Dublex',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Çatı Dubleks':
      veri["Tipi"][index] = "Dubleks"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Çatı Dubleks',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Çatı Katı':
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Çatı Katı',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Villa Tipi':
      veri["Tipi"][index] = "Villa"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Villa Tipi',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Bahçe Dublex':
      veri["Tipi"][index] = "Dubleks"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Bahçe Dublex',str(veri["Binanın Kat Sayısı"][index]))
for index, değişken in enumerate(veri['Bulunduğu Kat']):
  veri['Bulunduğu Kat'][index] = int(değişken)

veri['Bulunduğu Kat'].unique()

veri = veri.dropna()
veri = veri.reset_index(level=0, drop=True)

veri.isna().sum()

label_encoder = LabelEncoder()
veri['Yapı Durumu'] = label_encoder.fit_transform(veri['Yapı Durumu'])
veri['Oda Sayısı'] = label_encoder.fit_transform(veri['Oda Sayısı'])
veri['Isıtma Tipi'] = label_encoder.fit_transform(veri['Isıtma Tipi'])
veri['Site İçerisinde'] = label_encoder.fit_transform(veri['Site İçerisinde'])
veri['Fiyat Durumu'] = label_encoder.fit_transform(veri['Fiyat Durumu'])
veri['Tipi'] = label_encoder.fit_transform(veri['Tipi'])
veri['Binanın Yaşı'] = label_encoder.fit_transform(veri['Binanın Yaşı'])
veri['Tapu Durumu'] = label_encoder.fit_transform(veri['Tapu Durumu'])
veri['Konum'] = label_encoder.fit_transform(veri['Konum'])
veri['Krediye Uygunluk'] = label_encoder.fit_transform(veri['Krediye Uygunluk'])
veri['Eşya Durumu'] = label_encoder.fit_transform(veri['Eşya Durumu'])

veri.to_csv('düzenlenmiş_veri.csv', index=False)

